### ISSUE TITLE
cannot find test_ids gem

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/test_ids#4]
Hi,

Here is my gemspec file:

~~~ruby
spec.add_runtime_dependency 'test_ids', '~> 0.8.0'
~~~

and here is what i get:

~~~shell
peologin07:amd-test $ origen i
Bundler could not find compatible versions for gem "test_ids":
  In Gemfile:
    mygem was resolved to 0.82.1, which depends on
      test_ids (~> 0.8.0)

Could not find gem 'test_ids (~> 0.8.0)', which is required by gem 'amd_test', in any of the sources.
~~~

Any ideas?

**Comment by priyavadan** [comment]
@info-rchitect I assume you added  require 'test_ids'  in probably your interface or any other top level file? also running bundle install after that should help.

**Comment by ginty** [comment]
If this is a new app, you do have rubygems.org listed as a source in your Gemfile? i.e. could it only be considering your internal gem server?

Otherwise, I have no idea why this would not work, there is nothing special about this gem.

I have something slightly different in my gemspec which you might try:

~~~ruby
spec.add_runtime_dependency "test_ids", ">= 0.8.0"
~~~

**Comment by info-rchitect** [comment]
i had to manually run bundle install which seems odd but ohh well.
